//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineasDePedido
    {
        public int IdLineaDePedido { get; set; }
        public Nullable<int> NumeroPedido { get; set; }
        public Nullable<int> CodArticulo { get; set; }
        public Nullable<int> CantidadPedida { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
